name: salas_udp
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  
  csv: ^6.0.0
  file_picker: ^10.1.2
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.2.2
  intl : ^0.20.2
  collection: ^1.18.0
  font_awesome_flutter: ^10.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  
  assets:
    - imgns/imagen.jpg
